services:
  app:
    build: .
    restart: unless-stopped
    expose:
      - "3000"
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laportal.rule=Host(`laportal.montalvo.io`)"
      - "traefik.http.routers.laportal.entrypoints=websecure"
      - "traefik.http.routers.laportal.tls.certresolver=letsencrypt"
      - "traefik.http.services.laportal.loadbalancer.server.port=3000"
    networks:
      - default
      - traefik-net

networks:
  default:
    enable_ipv6: true
  traefik-net:
    external: true
