import type { PricingConfigUpdateInput } from "@/lib/pricing/validators";

export const defaultPrintPricingConfig: PricingConfigUpdateInput = {
  shopTitle: "Campus Print Shop",
  quotePrefix: "PSQ",
  quoteDisclaimer: "Final pricing subject to file review and production requirements.",
  taxEnabled: false,
  taxRateBasisPoints: 0,
  bwDuplexMultiplierBasisPoints: 17000,
  colorDuplexMultiplierBasisPoints: 18500,
  minimumScanChargeCents: 200,
  copyTiers: {
    BW: [
      {
        variant: "BW",
        label: "1-49 pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 1,
        maxQuantity: 49,
        unitPriceCents: 15,
        sortOrder: 0,
      },
      {
        variant: "BW",
        label: "50-249 pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 50,
        maxQuantity: 249,
        unitPriceCents: 13,
        sortOrder: 1,
      },
      {
        variant: "BW",
        label: "250-999 pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 250,
        maxQuantity: 999,
        unitPriceCents: 11,
        sortOrder: 2,
      },
      {
        variant: "BW",
        label: "1000+ pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 1000,
        maxQuantity: null,
        unitPriceCents: 10,
        sortOrder: 3,
      },
    ],
    COLOR: [
      {
        variant: "COLOR",
        label: "1-24 pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 1,
        maxQuantity: 24,
        unitPriceCents: 50,
        sortOrder: 0,
      },
      {
        variant: "COLOR",
        label: "25-99 pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 25,
        maxQuantity: 99,
        unitPriceCents: 47,
        sortOrder: 1,
      },
      {
        variant: "COLOR",
        label: "100-499 pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 100,
        maxQuantity: 499,
        unitPriceCents: 43,
        sortOrder: 2,
      },
      {
        variant: "COLOR",
        label: "500+ pages",
        description: "24 lb copy paper, single-sided",
        minQuantity: 500,
        maxQuantity: null,
        unitPriceCents: 39,
        sortOrder: 3,
      },
    ],
  },
  scanTiers: [
    {
      variant: "SCAN",
      label: "1-24 pages",
      description: "Per-page scanning rate",
      minQuantity: 1,
      maxQuantity: 24,
      unitPriceCents: 25,
      sortOrder: 0,
    },
    {
      variant: "SCAN",
      label: "25-99 pages",
      description: "Per-page scanning rate",
      minQuantity: 25,
      maxQuantity: 99,
      unitPriceCents: 18,
      sortOrder: 1,
    },
    {
      variant: "SCAN",
      label: "100+ pages",
      description: "Per-page scanning rate",
      minQuantity: 100,
      maxQuantity: null,
      unitPriceCents: 12,
      sortOrder: 2,
    },
  ],
  posterTiers: {
    LOW: {
      variant: "LOW",
      label: "Low",
      description: "Mostly text, linework, simple graphics, low ink coverage",
      unitPriceCents: 1500,
      sortOrder: 0,
    },
    MEDIUM: {
      variant: "MEDIUM",
      label: "Medium",
      description: "Mixed graphics and color blocks",
      unitPriceCents: 2200,
      sortOrder: 1,
    },
    HIGH: {
      variant: "HIGH",
      label: "High",
      description: "Photo-heavy, full-bleed, dense ink coverage",
      unitPriceCents: 3000,
      sortOrder: 2,
    },
  },
  bindingTiers: {
    COMB: {
      variant: "COMB",
      label: "Comb",
      description: "Flat binding price per item",
      unitPriceCents: 500,
      sortOrder: 0,
    },
    GLUE: {
      variant: "GLUE",
      label: "Glue",
      description: "Flat binding price per item",
      unitPriceCents: 500,
      sortOrder: 1,
    },
  },
};
