import type {
  BulkEditFieldGroup,
  BulkEditFieldId,
  BulkEditFieldRefOptionKey,
} from "@/domains/bulk-edit/types";

export type ProductEditableFieldGroup = BulkEditFieldGroup;

export type ProductEditablePatchTarget = "item" | "gm" | "textbook" | "inventory";

export type ProductEditableItemType = "general_merchandise" | "textbook" | "used_textbook";

export interface ProductEditableFieldDefinition {
  id: BulkEditFieldId;
  label: string;
  group: ProductEditableFieldGroup;
  patchTarget: ProductEditablePatchTarget;
  itemTypes: readonly ProductEditableItemType[];
  locationAware: boolean;
  requiresLocation: boolean;
  fillRateLabel: string;
  refSource?: BulkEditFieldRefOptionKey;
  refOptionKey?: BulkEditFieldRefOptionKey;
}

export interface ProductEditableFieldSection {
  group: ProductEditableFieldGroup;
  fields: readonly ProductEditableFieldDefinition[];
}

function defineField<const T extends ProductEditableFieldDefinition>(definition: T): T {
  return definition;
}

export const productEditableFieldSections = [
  {
    group: "primary",
    fields: [
      defineField({
        id: "description",
        label: "Description",
        group: "primary",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "100.0%",
      }),
      defineField({
        id: "title",
        label: "Title",
        group: "primary",
        patchTarget: "textbook",
        itemTypes: ["textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "100.0%",
      }),
      defineField({
        id: "author",
        label: "Author",
        group: "primary",
        patchTarget: "textbook",
        itemTypes: ["textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "100.0%",
      }),
      defineField({
        id: "isbn",
        label: "ISBN",
        group: "primary",
        patchTarget: "textbook",
        itemTypes: ["textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "91.8%",
      }),
      defineField({
        id: "edition",
        label: "Edition",
        group: "primary",
        patchTarget: "textbook",
        itemTypes: ["textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "65.4%",
      }),
      defineField({
        id: "bindingId",
        label: "Binding",
        group: "primary",
        patchTarget: "textbook",
        itemTypes: ["textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "82.9%",
        refSource: "bindings",
        refOptionKey: "bindings",
      }),
      defineField({
        id: "barcode",
        label: "Barcode",
        group: "primary",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "69.5% / 94.1%",
      }),
      defineField({
        id: "dccId",
        label: "DCC",
        group: "primary",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "100.0%",
        refSource: "dccs",
        refOptionKey: "dccs",
      }),
      defineField({
        id: "vendorId",
        label: "Vendor",
        group: "primary",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "100.0%",
        refSource: "vendors",
        refOptionKey: "vendors",
      }),
      defineField({
        id: "itemTaxTypeId",
        label: "Item Tax Type",
        group: "primary",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "100.0%",
        refSource: "taxTypes",
        refOptionKey: "taxTypes",
      }),
      defineField({
        id: "catalogNumber",
        label: "Catalog #",
        group: "primary",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "70.9%",
      }),
      defineField({
        id: "comment",
        label: "Comment",
        group: "primary",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "6.9% / 20.8%",
      }),
      defineField({
        id: "fDiscontinue",
        label: "Discontinue",
        group: "primary",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.2% / 0.7%",
      }),
    ],
  },
  {
    group: "inventory",
    fields: [
      defineField({
        id: "retail",
        label: "Retail",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "98.4% / 98.9%",
      }),
      defineField({
        id: "cost",
        label: "Cost",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "96.7% / 98.4%",
      }),
      defineField({
        id: "expectedCost",
        label: "Expected Cost",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "39.6% / 81.9%",
      }),
      defineField({
        id: "tagTypeId",
        label: "Tag Type",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "100.0% / 100.0%",
        refSource: "tagTypes",
        refOptionKey: "tagTypes",
      }),
      defineField({
        id: "statusCodeId",
        label: "Status Code",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "98.9% / 100.0%",
        refSource: "statusCodes",
        refOptionKey: "statusCodes",
      }),
      defineField({
        id: "estSales",
        label: "Est. Sales",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "39.3% / 84.2%",
      }),
      defineField({
        id: "fInvListPriceFlag",
        label: "Use inventory list price on price tag",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "95.3% / 81.3%",
      }),
      defineField({
        id: "fTxWantListFlag",
        label: "Want List",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "4.9% / 76.2%",
      }),
      defineField({
        id: "fTxBuybackListFlag",
        label: "Buyback List",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "4.9% / 75.4%",
      }),
      defineField({
        id: "fNoReturns",
        label: "No Returns",
        group: "inventory",
        patchTarget: "inventory",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: true,
        requiresLocation: true,
        fillRateLabel: "0.0% / 18.1%",
      }),
    ],
  },
  {
    group: "more",
    fields: [
      defineField({
        id: "packageType",
        label: "Package Type",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "100.0%",
        refSource: "packageTypes",
        refOptionKey: "packageTypes",
      }),
      defineField({
        id: "unitsPerPack",
        label: "Units per Pack",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "15.0%",
      }),
      defineField({
        id: "weight",
        label: "Weight",
        group: "more",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
      defineField({
        id: "imageUrl",
        label: "Image URL",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0% / 0.3%",
      }),
      defineField({
        id: "altVendorId",
        label: "Alt Vendor",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
        refSource: "vendors",
        refOptionKey: "vendors",
      }),
      defineField({
        id: "mfgId",
        label: "Manufacturer ID",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "6.1%",
      }),
      defineField({
        id: "size",
        label: "Size",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
      defineField({
        id: "colorId",
        label: "Color",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "29.0%",
        refSource: "colors",
        refOptionKey: "colors",
      }),
      defineField({
        id: "orderIncrement",
        label: "Order Increment",
        group: "more",
        patchTarget: "gm",
        itemTypes: ["general_merchandise"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
    ],
  },
  {
    group: "advanced",
    fields: [
      defineField({
        id: "styleId",
        label: "Style ID",
        group: "advanced",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
      defineField({
        id: "itemSeasonCodeId",
        label: "Season Code",
        group: "advanced",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
      defineField({
        id: "usedDccId",
        label: "Used DCC",
        group: "advanced",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
        refSource: "dccs",
        refOptionKey: "dccs",
      }),
      defineField({
        id: "minOrderQtyItem",
        label: "Min Order Qty",
        group: "advanced",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
      defineField({
        id: "fListPriceFlag",
        label: "List Price Flag",
        group: "advanced",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0% / 15.2%",
      }),
      defineField({
        id: "fPerishable",
        label: "Perishable",
        group: "advanced",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
      defineField({
        id: "fIdRequired",
        label: "ID Required",
        group: "advanced",
        patchTarget: "item",
        itemTypes: ["general_merchandise", "textbook", "used_textbook"],
        locationAware: false,
        requiresLocation: false,
        fillRateLabel: "0.0%",
      }),
    ],
  },
] as const satisfies readonly ProductEditableFieldSection[];

export const productEditableFieldRegistry = productEditableFieldSections.reduce(
  (registry, section) => {
    for (const field of section.fields) {
      registry[field.id] = field;
    }
    return registry;
  },
  {} as Record<BulkEditFieldId, ProductEditableFieldDefinition>,
);
