import type { ColumnPreferences, PresetGroup, ProductFilters, SavedView } from "./types";

type PresetSeed = {
  slug: string;
  name: string;
  description: string;
  presetGroup: PresetGroup;
  sortOrder: number;
  filter: Partial<ProductFilters>;
  columnPreferences: ColumnPreferences;
};

export const SYSTEM_PRESETS: PresetSeed[] = [
  // 💀 Dead weight
  { slug: "dead-discontinued-with-stock", name: "Discontinued with stock", description: "Items marked discontinued that still have stock on hand.",
    presetGroup: "dead-weight", sortOrder: 10,
    filter: { discontinued: "yes", minStock: "1" },
    columnPreferences: { visible: ["updated"] } },
  { slug: "dead-never-sold-authoritative", name: "Never sold at Pierce (3y base)", description: "No transactions on record at Pierce. Uses real txn history.",
    presetGroup: "dead-weight", sortOrder: 20,
    filter: { neverSoldLifetime: true },
    columnPreferences: { visible: ["updated"] } },
  { slug: "dead-never-sold-with-stock", name: "Never sold + still in stock", description: "No txn history AND stock on hand. Strongest clearance signal.",
    presetGroup: "dead-weight", sortOrder: 30,
    filter: { neverSoldLifetime: true, minStock: "1" },
    columnPreferences: { visible: ["updated"] } },
  { slug: "dead-no-sales-1y-stock", name: "No sales in 1y, stocked", description: "Zero units sold in trailing year AND stock on hand.",
    presetGroup: "dead-weight", sortOrder: 40,
    filter: { unitsSoldWindow: "1y", maxUnitsSold: "0", minStock: "1" },
    columnPreferences: { visible: ["units_1y", "updated"] } },
  { slug: "dead-no-sales-2y-stock", name: "No sales in 2y, stocked", description: "Last sale more than 2y ago AND stock on hand.",
    presetGroup: "dead-weight", sortOrder: 50,
    filter: { lastSaleOlderThan: "2y", minStock: "1" },
    columnPreferences: { visible: ["days_since_sale"] } },
  { slug: "dead-discontinued-with-recent-sales", name: "Discontinued but still moving", description: "Items flagged discontinued that nonetheless sold in the last year. Probable mis-flags.",
    presetGroup: "dead-weight", sortOrder: 60,
    filter: { discontinued: "yes", unitsSoldWindow: "1y", minUnitsSold: "1" },
    columnPreferences: { visible: ["units_1y", "updated"] } },

  // 📊 Movers
  { slug: "movers-top-units-30d", name: "Top sellers (units) last 30 days", description: "Most units sold in the trailing 30 days.",
    presetGroup: "movers", sortOrder: 10,
    filter: { unitsSoldWindow: "30d", minUnitsSold: "1", sortBy: "units_sold_30d", sortDir: "desc" },
    columnPreferences: { visible: ["units_1y", "revenue_1y"] } },
  { slug: "movers-top-units-1y", name: "Top sellers (units) last year", description: "Most units sold in the trailing year.",
    presetGroup: "movers", sortOrder: 20,
    filter: { unitsSoldWindow: "1y", minUnitsSold: "1", sortBy: "units_sold_1y", sortDir: "desc" },
    columnPreferences: { visible: ["units_1y", "revenue_1y"] } },
  { slug: "movers-top-units-lifetime", name: "Top sellers (units) lifetime", description: "Most units sold across our 3y+ base.",
    presetGroup: "movers", sortOrder: 30,
    filter: { unitsSoldWindow: "lifetime", minUnitsSold: "1", sortBy: "units_sold_lifetime", sortDir: "desc" },
    columnPreferences: { visible: ["units_1y", "revenue_1y"] } },
  { slug: "movers-top-revenue-30d", name: "Top revenue last 30 days", description: "Highest dollar sales in the trailing 30 days.",
    presetGroup: "movers", sortOrder: 40,
    filter: { revenueWindow: "30d", minRevenue: "1", sortBy: "revenue_30d", sortDir: "desc" },
    columnPreferences: { visible: ["revenue_1y", "units_1y", "margin"] } },
  { slug: "movers-top-revenue-1y", name: "Top revenue last year", description: "Highest dollar sales in the trailing year.",
    presetGroup: "movers", sortOrder: 50,
    filter: { revenueWindow: "1y", minRevenue: "1", sortBy: "revenue_1y", sortDir: "desc" },
    columnPreferences: { visible: ["revenue_1y", "units_1y", "margin"] } },
  { slug: "movers-consistent-sellers", name: "Consistent sellers (50+ receipts/yr)", description: "Sold across 50+ distinct receipts in the last year — not a bulk-order fluke.",
    presetGroup: "movers", sortOrder: 60,
    filter: { txnsWindow: "1y", minTxns: "50", sortBy: "txns_1y", sortDir: "desc" },
    columnPreferences: { visible: ["txns_1y", "units_1y", "revenue_1y"] } },
  { slug: "movers-one-hit-wonders", name: "Big-volume one-time sales", description: "Sold 10+ units but across only one receipt lifetime — usually a single course adoption.",
    presetGroup: "movers", sortOrder: 70,
    filter: { txnsWindow: "lifetime", maxTxns: "1", unitsSoldWindow: "lifetime", minUnitsSold: "10" },
    columnPreferences: { visible: ["units_1y", "txns_1y"] } },

  // 📈 Trending
  { slug: "trend-accelerating", name: "Accelerating", description: "30-day daily rate > 1.5× trailing-1y daily rate.",
    presetGroup: "trending", sortOrder: 10,
    filter: { trendDirection: "accelerating", unitsSoldWindow: "30d", minUnitsSold: "5" },
    columnPreferences: { visible: ["units_1y"] } },
  { slug: "trend-decelerating", name: "Decelerating", description: "30-day daily rate < 0.5× trailing-1y daily rate.",
    presetGroup: "trending", sortOrder: 20,
    filter: { trendDirection: "decelerating", unitsSoldWindow: "1y", minUnitsSold: "10" },
    columnPreferences: { visible: ["units_1y"] } },
  { slug: "trend-new-arrivals", name: "New & moving", description: "First seen in last 90 days and already moving.",
    presetGroup: "trending", sortOrder: 30,
    filter: { firstSaleWithin: "90d", unitsSoldWindow: "30d", minUnitsSold: "5" },
    columnPreferences: { visible: ["units_1y", "revenue_1y"] } },

  // 📦 Stock health
  { slug: "stock-stockout-risk", name: "Stockout risk", description: "Stock <= 2 and selling well in the last 30 days — reorder now.",
    presetGroup: "stock-health", sortOrder: 10,
    filter: { maxStock: "2", unitsSoldWindow: "30d", minUnitsSold: "5" },
    columnPreferences: { visible: ["units_1y"] } },
  { slug: "stock-less-than-30d-cover", name: "Less than 30 days of cover", description: "At current pace will run out within 30 days.",
    presetGroup: "stock-health", sortOrder: 20,
    filter: { maxStockCoverageDays: "30", unitsSoldWindow: "30d", minUnitsSold: "1" },
    columnPreferences: { visible: ["units_1y"] } },
  { slug: "stock-stale-stock", name: "Stale stock (2y+ idle)", description: ">=10 units on hand but no sale in the last 2 years.",
    presetGroup: "stock-health", sortOrder: 30,
    filter: { minStock: "10", lastSaleOlderThan: "2y" },
    columnPreferences: { visible: ["days_since_sale"] } },

  // 💰 Pricing
  { slug: "pricing-gm-under-5", name: "GM under $5", description: "General merchandise priced under $5.",
    presetGroup: "pricing", sortOrder: 10,
    filter: { tab: "merchandise", maxPrice: "5" },
    columnPreferences: { visible: ["margin", "units_1y"] } },
  { slug: "pricing-gm-over-50", name: "GM over $50", description: "General merchandise priced over $50.",
    presetGroup: "pricing", sortOrder: 20,
    filter: { tab: "merchandise", minPrice: "50" },
    columnPreferences: { visible: ["margin", "units_1y"] } },
  { slug: "pricing-textbooks-over-100", name: "Textbooks over $100", description: "Textbooks priced over $100.",
    presetGroup: "pricing", sortOrder: 30,
    filter: { tab: "textbooks", minPrice: "100" },
    columnPreferences: { visible: ["margin", "units_1y"] } },
  { slug: "price-high-margin-high-velocity", name: "High margin + high velocity", description: "Margin >40% and 50+ units sold last year. Cash cows.",
    presetGroup: "pricing", sortOrder: 40,
    filter: { minMargin: "0.4", unitsSoldWindow: "1y", minUnitsSold: "50" },
    columnPreferences: { visible: ["margin", "units_1y", "revenue_1y"] } },
  { slug: "price-high-margin-dead", name: "High margin + not moving", description: "Margin >40% but zero units last year. Priced fine, nobody wants it.",
    presetGroup: "pricing", sortOrder: 50,
    filter: { minMargin: "0.4", unitsSoldWindow: "1y", maxUnitsSold: "0" },
    columnPreferences: { visible: ["margin", "units_1y"] } },
  { slug: "price-thin-margin-popular", name: "Thin margin + popular (raise price?)", description: "Margin <10% and 100+ units last year. Candidates for a price bump.",
    presetGroup: "pricing", sortOrder: 60,
    filter: { maxMargin: "0.1", unitsSoldWindow: "1y", minUnitsSold: "100" },
    columnPreferences: { visible: ["margin", "units_1y", "revenue_1y"] } },
  { slug: "price-low-revenue-high-stock", name: "Low revenue, high stock", description: "Revenue <$50 last year but 20+ units on hand.",
    presetGroup: "pricing", sortOrder: 70,
    filter: { revenueWindow: "1y", maxRevenue: "50", minStock: "20" },
    columnPreferences: { visible: ["revenue_1y"] } },

  // 🎓 Textbook
  { slug: "textbook-used-only", name: "Used textbooks only", description: "Used-copy textbook SKUs.",
    presetGroup: "textbook", sortOrder: 10,
    filter: { itemType: "used_textbook" },
    columnPreferences: { visible: ["units_1y"] } },
  { slug: "textbook-current-semester-active", name: "Textbook active this semester", description: "Textbook with 5+ units sold in the last 90 days.",
    presetGroup: "textbook", sortOrder: 20,
    filter: { tab: "textbooks", unitsSoldWindow: "90d", minUnitsSold: "5" },
    columnPreferences: { visible: ["units_1y"] } },
  { slug: "textbook-used-moving", name: "Used textbooks moving", description: "Used-copy SKU with any sale in the last 90 days.",
    presetGroup: "textbook", sortOrder: 30,
    filter: { itemType: "used_textbook", unitsSoldWindow: "90d", minUnitsSold: "1" },
    columnPreferences: { visible: ["units_1y"] } },
  { slug: "textbook-faded-this-year", name: "Textbook faded (was active, now quiet)", description: "Textbooks with sales in last year but zero in last 30 days.",
    presetGroup: "textbook", sortOrder: 40,
    filter: { tab: "textbooks", unitsSoldWindow: "30d", maxUnitsSold: "0" },
    columnPreferences: { visible: ["units_1y"] } },

  // 🔍 Data quality (kept)
  { slug: "data-missing-barcode", name: "Missing barcode", description: "Items with no barcode on file.",
    presetGroup: "data-quality", sortOrder: 10,
    filter: { missingBarcode: true },
    columnPreferences: { visible: ["updated"] } },
  { slug: "data-missing-isbn-textbook", name: "Missing ISBN (textbooks)", description: "Textbooks with no ISBN.",
    presetGroup: "data-quality", sortOrder: 20,
    filter: { tab: "textbooks", missingIsbn: true },
    columnPreferences: { visible: ["updated"] } },
  { slug: "data-missing-title-or-description", name: "Missing description or title", description: "Textbooks without a title, or general merchandise without a description.",
    presetGroup: "data-quality", sortOrder: 30,
    filter: { missingTitle: true },
    columnPreferences: { visible: ["updated"] } },
  { slug: "data-retail-below-cost", name: "Retail < cost", description: "Retail price lower than cost. Usually a data entry error.",
    presetGroup: "data-quality", sortOrder: 40,
    filter: { retailBelowCost: true },
    columnPreferences: { visible: ["margin", "updated"] } },
  { slug: "data-zero-price", name: "Retail or cost = 0", description: "Retail or cost is exactly zero.",
    presetGroup: "data-quality", sortOrder: 50,
    filter: { zeroPrice: true },
    columnPreferences: { visible: ["updated"] } },

  // 📝 Recent activity (kept)
  { slug: "recent-edited-7d", name: "Edited in last 7 days", description: "Items modified in the past week.",
    presetGroup: "recent-activity", sortOrder: 10,
    filter: { editedWithin: "7d" },
    columnPreferences: { visible: ["updated"] } },
  { slug: "recent-edited-since-sync", name: "Edited since last sync", description: "Items whose row was touched after the mirror was last refreshed.",
    presetGroup: "recent-activity", sortOrder: 20,
    filter: { editedSinceSync: true },
    columnPreferences: { visible: ["updated"] } },
];

export function presetSeedToSavedView(seed: PresetSeed): SavedView {
  return {
    id: seed.slug,
    name: seed.name,
    description: seed.description,
    filter: seed.filter,
    columnPreferences: seed.columnPreferences,
    isSystem: true,
    slug: seed.slug,
    presetGroup: seed.presetGroup,
    sortOrder: seed.sortOrder,
  };
}

export const SYSTEM_PRESET_VIEWS: SavedView[] = SYSTEM_PRESETS.map(presetSeedToSavedView);
