import { describe, expect, it } from "vitest";
import type { PrismItemRow, PrismInventoryRow } from "@/domains/product/prism-sync";

describe("Prism sync row types", () => {
  it("PrismItemRow carries only global (per-SKU) fields", () => {
    const row: PrismItemRow = {
      sku: 123,
      description: "Test",
      title: null,
      author: null,
      isbn: null,
      edition: null,
      binding_id: null,
      binding_label: null,
      imprint: null,
      copyright: null,
      usedSku: null,
      textStatusId: null,
      statusDate: null,
      typeTextbook: null,
      bookKey: null,
      barcode: null,
      vendorId: 100,
      altVendorId: null,
      mfgId: null,
      dccId: 1010,
      usedDccId: null,
      itemTaxTypeId: 4,
      itemTaxTypeLabel: "STATE",
      itemType: "general_merchandise",
      fDiscontinue: 0,
      txComment: null,
      weight: null,
      styleId: null,
      itemSeasonCodeId: null,
      fListPriceFlag: 0,
      fPerishable: 0,
      fIdRequired: 0,
      minOrderQtyItem: null,
      typeGm: null,
      size: null,
      sizeId: null,
      catalogNumber: null,
      packageType: "EA",
      packageTypeLabel: "Each",
      unitsPerPack: null,
      orderIncrement: 1,
      imageUrl: null,
      useScaleInterface: 0,
      tare: null,
      deptNum: 10,
      classNum: 10,
      catNum: 20,
      deptName: "Drinks",
      className: "Bottled",
      catName: "Sodas",
    };
    expect(row.sku).toBe(123);
    expect(row.itemTaxTypeLabel).toBe("STATE");
  });

  it("PrismInventoryRow carries exactly one (sku, locationId) pair", () => {
    const row: PrismInventoryRow = {
      sku: 123,
      locationId: 2,
      locationAbbrev: "PIER",
      retail: 9.99,
      cost: 4.5,
      expectedCost: null,
      stockOnHand: 12,
      tagTypeId: 3,
      tagTypeLabel: "LARGE w/Price/Color",
      statusCodeId: 2,
      statusCodeLabel: "Active",
      taxTypeOverrideId: null,
      discCodeId: null,
      minStock: null,
      maxStock: null,
      autoOrderQty: null,
      minOrderQty: null,
      holdQty: null,
      reservedQty: null,
      rentalQty: null,
      estSales: null,
      estSalesLocked: 0,
      royaltyCost: null,
      minRoyaltyCost: null,
      fInvListPriceFlag: 1,
      fTxWantListFlag: 0,
      fTxBuybackListFlag: 0,
      fRentOnly: 0,
      fNoReturns: 0,
      textCommentInv: null,
      lastSaleDate: new Date("2026-04-01T00:00:00Z"),
      lastInventoryDate: null,
      createDate: null,
    };
    expect(row.locationId).toBe(2);
    expect([2, 3, 4]).toContain(row.locationId);
  });
});
